version: 0.3

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo "Installing dependencies or performing any necessary setup steps"

  build:
    commands:
      - echo "Building your project"

  post_build:
    commands:
      - echo "Performing post-build actions or tests"

artifacts:
  files:
    - '**/*'
